# Generated by Django 3.2 on 2021-04-28 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('net4', models.GenericIPAddressField(protocol='ipv4')),
                ('mask4', models.IntegerField(choices=[(24, '/24'), (25, '/25'), (26, '/26'), (27, '/27'), (28, '/28'), (29, '/29'), (30, '/30')], default=24)),
                ('net6', models.GenericIPAddressField(protocol='ipv6')),
                ('mask6', models.IntegerField(choices=[(64, '/64')], default=64)),
                ('created', models.TimeField(auto_now_add=True)),
                ('modified', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ip4', models.GenericIPAddressField(protocol='ipv4')),
                ('ip6', models.GenericIPAddressField(protocol='ipv6')),
                ('created', models.TimeField(auto_now_add=True)),
                ('modified', models.TimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privatekey', models.CharField(max_length=44)),
                ('publickey', models.CharField(max_length=44)),
                ('created', models.TimeField(auto_now_add=True)),
                ('modified', models.TimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.host')),
            ],
        ),
    ]
