# Generated by Django 3.2 on 2021-04-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_keys_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='net4',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv4'),
        ),
        migrations.AlterField(
            model_name='group',
            name='net6',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv6'),
        ),
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip4',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv4'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip6',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv6'),
        ),
    ]
