# Generated by Django 3.2 on 2021-04-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210428_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
