# Generated by Django 3.2 on 2021-04-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_host_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='group',
        ),
    ]
