# Generated by Django 3.2 on 2021-04-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_host_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created', models.TimeField(auto_now_add=True)),
                ('modified', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='key',
            name='ip4',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv4'),
        ),
        migrations.AddField(
            model_name='key',
            name='ip6',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv6'),
        ),
        migrations.AddField(
            model_name='key',
            name='master',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.peer'),
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
