# Generated by Django 3.2 on 2021-04-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210428_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='host',
            new_name='peer',
        ),
    ]
