# Generated by Django 3.2 on 2021-04-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_host_key_peer'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='endpoint',
            field=models.CharField(default='host:port', max_length=128),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='peer',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
